### PR TITLE
Demonstration Primarily For NNH At PyRenew Meeting

### PR DESCRIPTION
**Pull request by AFg6K7h4fhy2**
The scope of this PR can be found in Issue #31 .

### CODE REVIEW

**Comment by AFg6K7h4fhy2** [comment]
The demonstration lives temporarily in #35, since PR 35 has major un-merged changes that are important for the demonstration. Right before PR 35 gets merged to `main`, the demonstration will be moved back to this PR. Then, the changes from PR 35 will be pulled from `main` into this PR and this PR will get merged to `main` (with the demo. notebook).

**Comment by AFg6K7h4fhy2** [comment]
What was shown during the demonstration was an HTML file produced by running 

```
quarto render forecasttools_community_demo_2024-11-19.qmd
```

The HTML file was clicked on an displayed in the most recent version of the FireFox browser.

**Comment by AFg6K7h4fhy2** [comment]
An open question is whether this notebook should exist in its current form in this repository. The author's belief is that it should, conditionally possibly on the presence of two contextual statements, one in the README (describing the notebooks) and another in `forecasttools_community_demo_2024-11-19.qmd` describing the context for the presentation.

**Comment by dylanhmorris** [comment]
I think it should be in the repo, eventually as part of the formal documentation. For now it can live in a `notebooks` directory, since I think documentation is a much larger lift.

**Pull request merged**
